### ISSUE TITLE
rss feed?

### ISSUE THREAD

**Issue by bitboxer** [ElijahPepe/elonstwitterisgoinggreat#1]
Awesome page ♥️. Would love to have an rss feed on this. If you don't mind I would create a little PR that adds this?

**Comment by ElijahPepe** [comment]
Sure, I can do that.

**Comment by ElijahPepe** [comment]
Feed is available at https://elonstwitterisgoinggreat.com/feed.xml.

**Comment by bitboxer** [comment]
Awesome. Thank you.
